version: '3.8'

services:
  web:
    build: .
    command: bash startup.sh
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_root:fastapi_root@db:5432/fastapi_root
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # expose:
    #   - 5432
    environment:
      - POSTGRES_USER=fastapi_root
      - POSTGRES_PASSWORD=fastapi_root
      - POSTGRES_DB=fastapi_root
      #- POSTGRES_HOST=localhost
    ports:
      - "5432:5432"

volumes:
  postgres_data:
